#!/bin/bash

if [ "$1" == "" ]
then
echo "forgor ip address :< !"
echo "Syntax: ./ipsweep.sh 192.168.1"

else
for ip in `seq 1 254`; do
ping -c 1 $1.$ip | grep "64 bytes" | cut -d " " -f 4 | tr -d ":" &
done
fi

#This code is for personal use only but i thought to add since its the first port scanner i made wit bash ٩(^ᴗ^)۶ ! 
